// Code generated by autotask-gen. DO NOT EDIT.
package entities

import (
	"time"

	autotask "github.com/tphakala/go-autotask"
)

// BillingItemApprovalLevel represents an Autotask BillingItemApprovalLevel entity.
type BillingItemApprovalLevel struct {
	ApprovalDateTime   autotask.Optional[time.Time] `json:"approvalDateTime,omitzero"`
	ApprovalLevel      autotask.Optional[int64]     `json:"approvalLevel,omitzero"`
	ApprovalResourceID autotask.Optional[int64]     `json:"approvalResourceID,omitzero"`
	Id                 autotask.Optional[int64]     `json:"id,omitzero"`
	TimeEntryID        autotask.Optional[int64]     `json:"timeEntryID,omitzero"`
	UserDefinedFields  []autotask.UDF               `json:"userDefinedFields,omitempty"`
}

func (BillingItemApprovalLevel) EntityName() string { return "BillingItemApprovalLevels" }
