// Code generated by autotask-gen. DO NOT EDIT.
package entities

import (
	autotask "github.com/tphakala/go-autotask"
)

// BillingCode represents an Autotask BillingCode entity.
type BillingCode struct {
	AfterHoursWorkType         autotask.Optional[int64]   `json:"afterHoursWorkType,omitzero"`
	BillingCodeType            autotask.Optional[int64]   `json:"billingCodeType,omitzero"`
	Department                 autotask.Optional[int64]   `json:"department,omitzero"`
	Description                autotask.Optional[string]  `json:"description,omitzero"`
	ExternalNumber             autotask.Optional[string]  `json:"externalNumber,omitzero"`
	GeneralLedgerAccount       autotask.Optional[int64]   `json:"generalLedgerAccount,omitzero"`
	Id                         autotask.Optional[int64]   `json:"id,omitzero"`
	IsActive                   autotask.Optional[bool]    `json:"isActive,omitzero"`
	IsExcludedFromNewContracts autotask.Optional[bool]    `json:"isExcludedFromNewContracts,omitzero"`
	MarkupRate                 autotask.Optional[float64] `json:"markupRate,omitzero"`
	Name                       autotask.Optional[string]  `json:"name,omitzero"`
	TaxCategoryID              autotask.Optional[int64]   `json:"taxCategoryID,omitzero"`
	UnitCost                   autotask.Optional[float64] `json:"unitCost,omitzero"`
	UnitPrice                  autotask.Optional[float64] `json:"unitPrice,omitzero"`
	UseType                    autotask.Optional[int64]   `json:"useType,omitzero"`
	UserDefinedFields          []autotask.UDF             `json:"userDefinedFields,omitempty"`
}

func (BillingCode) EntityName() string { return "BillingCodes" }
