// Code generated by autotask-gen. DO NOT EDIT.
package entities

import (
	"time"

	autotask "github.com/tphakala/go-autotask"
)

// BillingItem represents an Autotask BillingItem entity.
type BillingItem struct {
	AccountManagerWhenApprovedID      autotask.Optional[int64]     `json:"accountManagerWhenApprovedID,omitzero"`
	BillingCodeID                     autotask.Optional[int64]     `json:"billingCodeID,omitzero"`
	BillingItemType                   autotask.Optional[int64]     `json:"billingItemType,omitzero"`
	CompanyID                         autotask.Optional[int64]     `json:"companyID,omitzero"`
	ConfigurationItemID               autotask.Optional[int64]     `json:"configurationItemID,omitzero"`
	ContractBlockID                   autotask.Optional[int64]     `json:"contractBlockID,omitzero"`
	ContractChargeID                  autotask.Optional[int64]     `json:"contractChargeID,omitzero"`
	ContractID                        autotask.Optional[int64]     `json:"contractID,omitzero"`
	ContractServiceAdjustmentID       autotask.Optional[int64]     `json:"contractServiceAdjustmentID,omitzero"`
	ContractServiceBundleAdjustmentID autotask.Optional[int64]     `json:"contractServiceBundleAdjustmentID,omitzero"`
	ContractServiceBundleID           autotask.Optional[int64]     `json:"contractServiceBundleID,omitzero"`
	ContractServiceBundlePeriodID     autotask.Optional[int64]     `json:"contractServiceBundlePeriodID,omitzero"`
	ContractServiceID                 autotask.Optional[int64]     `json:"contractServiceID,omitzero"`
	ContractServicePeriodID           autotask.Optional[int64]     `json:"contractServicePeriodID,omitzero"`
	Description                       autotask.Optional[string]    `json:"description,omitzero"`
	ExpenseItemID                     autotask.Optional[int64]     `json:"expenseItemID,omitzero"`
	ExtendedPrice                     autotask.Optional[float64]   `json:"extendedPrice,omitzero"`
	Id                                autotask.Optional[int64]     `json:"id,omitzero"`
	InternalCurrencyExtendedPrice     autotask.Optional[float64]   `json:"internalCurrencyExtendedPrice,omitzero"`
	InternalCurrencyRate              autotask.Optional[float64]   `json:"internalCurrencyRate,omitzero"`
	InternalCurrencyTaxDollars        autotask.Optional[float64]   `json:"internalCurrencyTaxDollars,omitzero"`
	InternalCurrencyTotalAmount       autotask.Optional[float64]   `json:"internalCurrencyTotalAmount,omitzero"`
	InvoiceID                         autotask.Optional[int64]     `json:"invoiceID,omitzero"`
	ItemApproverID                    autotask.Optional[int64]     `json:"itemApproverID,omitzero"`
	ItemDate                          autotask.Optional[time.Time] `json:"itemDate,omitzero"`
	ItemName                          autotask.Optional[string]    `json:"itemName,omitzero"`
	LineItemFullDescription           autotask.Optional[string]    `json:"lineItemFullDescription,omitzero"`
	LineItemGroupDescription          autotask.Optional[string]    `json:"lineItemGroupDescription,omitzero"`
	MilestoneID                       autotask.Optional[int64]     `json:"milestoneID,omitzero"`
	NonBillable                       autotask.Optional[int64]     `json:"nonBillable,omitzero"`
	OrganizationalLevelAssociationID  autotask.Optional[int64]     `json:"organizationalLevelAssociationID,omitzero"`
	OurCost                           autotask.Optional[float64]   `json:"ourCost,omitzero"`
	PostedDate                        autotask.Optional[time.Time] `json:"postedDate,omitzero"`
	PostedOnTime                      autotask.Optional[time.Time] `json:"postedOnTime,omitzero"`
	ProjectChargeID                   autotask.Optional[int64]     `json:"projectChargeID,omitzero"`
	ProjectID                         autotask.Optional[int64]     `json:"projectID,omitzero"`
	PurchaseOrderNumber               autotask.Optional[string]    `json:"purchaseOrderNumber,omitzero"`
	Quantity                          autotask.Optional[float64]   `json:"quantity,omitzero"`
	Rate                              autotask.Optional[float64]   `json:"rate,omitzero"`
	RoleID                            autotask.Optional[int64]     `json:"roleID,omitzero"`
	ServiceBundleID                   autotask.Optional[int64]     `json:"serviceBundleID,omitzero"`
	ServiceID                         autotask.Optional[int64]     `json:"serviceID,omitzero"`
	SortOrderID                       autotask.Optional[int64]     `json:"sortOrderID,omitzero"`
	SubType                           autotask.Optional[int64]     `json:"subType,omitzero"`
	TaskID                            autotask.Optional[int64]     `json:"taskID,omitzero"`
	TaxCategoryID                     autotask.Optional[int64]     `json:"taxCategoryID,omitzero"`
	TaxDollars                        autotask.Optional[float64]   `json:"taxDollars,omitzero"`
	TicketChargeID                    autotask.Optional[int64]     `json:"ticketChargeID,omitzero"`
	TicketID                          autotask.Optional[int64]     `json:"ticketID,omitzero"`
	TimeEntryID                       autotask.Optional[int64]     `json:"timeEntryID,omitzero"`
	TotalAmount                       autotask.Optional[float64]   `json:"totalAmount,omitzero"`
	VendorID                          autotask.Optional[int64]     `json:"vendorID,omitzero"`
	WebServiceDate                    autotask.Optional[time.Time] `json:"webServiceDate,omitzero"`
	UserDefinedFields                 []autotask.UDF               `json:"userDefinedFields,omitempty"`
}

func (BillingItem) EntityName() string { return "BillingItems" }
