// Code generated by autotask-gen. DO NOT EDIT.
package entities

import (
	"time"

	autotask "github.com/tphakala/go-autotask"
)

// CompanyNote represents an Autotask CompanyNote entity.
type CompanyNote struct {
	ActionType                    autotask.Optional[int64]     `json:"actionType,omitzero"`
	AssignedResourceID            autotask.Optional[int64]     `json:"assignedResourceID,omitzero"`
	CompanyID                     autotask.Optional[int64]     `json:"companyID,omitzero"`
	CompletedDateTime             autotask.Optional[time.Time] `json:"completedDateTime,omitzero"`
	ContactID                     autotask.Optional[int64]     `json:"contactID,omitzero"`
	CreateDateTime                autotask.Optional[time.Time] `json:"createDateTime,omitzero"`
	EndDateTime                   autotask.Optional[time.Time] `json:"endDateTime,omitzero"`
	Id                            autotask.Optional[int64]     `json:"id,omitzero"`
	ImpersonatorCreatorResourceID autotask.Optional[int64]     `json:"impersonatorCreatorResourceID,omitzero"`
	ImpersonatorUpdaterResourceID autotask.Optional[int64]     `json:"impersonatorUpdaterResourceID,omitzero"`
	LastModifiedDate              autotask.Optional[time.Time] `json:"lastModifiedDate,omitzero"`
	Name                          autotask.Optional[string]    `json:"name,omitzero"`
	Note                          autotask.Optional[string]    `json:"note,omitzero"`
	OpportunityID                 autotask.Optional[int64]     `json:"opportunityID,omitzero"`
	StartDateTime                 autotask.Optional[time.Time] `json:"startDateTime,omitzero"`
	UserDefinedFields             []autotask.UDF               `json:"userDefinedFields,omitempty"`
}

func (CompanyNote) EntityName() string { return "CompanyNotes" }
