// Code generated by autotask-gen. DO NOT EDIT.
package entities

import (
	autotask "github.com/tphakala/go-autotask"
)

// Department represents an Autotask Department entity.
type Department struct {
	Description       autotask.Optional[string] `json:"description,omitzero"`
	Id                autotask.Optional[int64]  `json:"id,omitzero"`
	Name              autotask.Optional[string] `json:"name,omitzero"`
	Number            autotask.Optional[string] `json:"number,omitzero"`
	PrimaryLocationID autotask.Optional[int64]  `json:"primaryLocationID,omitzero"`
	UserDefinedFields []autotask.UDF            `json:"userDefinedFields,omitempty"`
}

func (Department) EntityName() string { return "Departments" }
