// Code generated by autotask-gen. DO NOT EDIT.
package entities

import (
	"time"

	autotask "github.com/tphakala/go-autotask"
)

// ExpenseItem represents an Autotask ExpenseItem entity.
type ExpenseItem struct {
	CompanyID                                autotask.Optional[int64]     `json:"companyID,omitzero"`
	Description                              autotask.Optional[string]    `json:"description,omitzero"`
	Destination                              autotask.Optional[string]    `json:"destination,omitzero"`
	EntertainmentLocation                    autotask.Optional[string]    `json:"entertainmentLocation,omitzero"`
	ExpenseCategory                          autotask.Optional[int64]     `json:"expenseCategory,omitzero"`
	ExpenseCurrencyExpenseAmount             autotask.Optional[float64]   `json:"expenseCurrencyExpenseAmount,omitzero"`
	ExpenseCurrencyID                        autotask.Optional[int64]     `json:"expenseCurrencyID,omitzero"`
	ExpenseDate                              autotask.Optional[time.Time] `json:"expenseDate,omitzero"`
	ExpenseReportID                          autotask.Optional[int64]     `json:"expenseReportID,omitzero"`
	GLCode                                   autotask.Optional[string]    `json:"gLCode,omitzero"`
	HaveReceipt                              autotask.Optional[bool]      `json:"haveReceipt,omitzero"`
	Id                                       autotask.Optional[int64]     `json:"id,omitzero"`
	InternalCurrencyExpenseAmount            autotask.Optional[float64]   `json:"internalCurrencyExpenseAmount,omitzero"`
	InternalCurrencyReimbursementAmount      autotask.Optional[float64]   `json:"internalCurrencyReimbursementAmount,omitzero"`
	IsBillableToCompany                      autotask.Optional[bool]      `json:"isBillableToCompany,omitzero"`
	IsReimbursable                           autotask.Optional[bool]      `json:"isReimbursable,omitzero"`
	IsRejected                               autotask.Optional[bool]      `json:"isRejected,omitzero"`
	Miles                                    autotask.Optional[float64]   `json:"miles,omitzero"`
	OdometerEnd                              autotask.Optional[float64]   `json:"odometerEnd,omitzero"`
	OdometerStart                            autotask.Optional[float64]   `json:"odometerStart,omitzero"`
	Origin                                   autotask.Optional[string]    `json:"origin,omitzero"`
	PaymentType                              autotask.Optional[int64]     `json:"paymentType,omitzero"`
	ProjectID                                autotask.Optional[int64]     `json:"projectID,omitzero"`
	PurchaseOrderNumber                      autotask.Optional[string]    `json:"purchaseOrderNumber,omitzero"`
	ReimbursementCurrencyReimbursementAmount autotask.Optional[float64]   `json:"reimbursementCurrencyReimbursementAmount,omitzero"`
	TaskID                                   autotask.Optional[int64]     `json:"taskID,omitzero"`
	TicketID                                 autotask.Optional[int64]     `json:"ticketID,omitzero"`
	WorkType                                 autotask.Optional[int64]     `json:"workType,omitzero"`
	UserDefinedFields                        []autotask.UDF               `json:"userDefinedFields,omitempty"`
}

func (ExpenseItem) EntityName() string { return "ExpenseItems" }
