// Code generated by autotask-gen. DO NOT EDIT.
package entities

import (
	"time"

	autotask "github.com/tphakala/go-autotask"
)

// ExpenseReport represents an Autotask ExpenseReport entity.
type ExpenseReport struct {
	AmountDue                              autotask.Optional[float64]   `json:"amountDue,omitzero"`
	ApprovedDate                           autotask.Optional[time.Time] `json:"approvedDate,omitzero"`
	ApproverID                             autotask.Optional[int64]     `json:"approverID,omitzero"`
	DepartmentNumber                       autotask.Optional[string]    `json:"departmentNumber,omitzero"`
	Id                                     autotask.Optional[int64]     `json:"id,omitzero"`
	InternalCurrencyCashAdvanceAmount      autotask.Optional[float64]   `json:"internalCurrencyCashAdvanceAmount,omitzero"`
	InternalCurrencyExpenseTotal           autotask.Optional[float64]   `json:"internalCurrencyExpenseTotal,omitzero"`
	Name                                   autotask.Optional[string]    `json:"name,omitzero"`
	OrganizationalLevelAssociationID       autotask.Optional[int64]     `json:"organizationalLevelAssociationID,omitzero"`
	QuickBooksReferenceNumber              autotask.Optional[string]    `json:"quickBooksReferenceNumber,omitzero"`
	ReimbursementCurrencyAmountDue         autotask.Optional[float64]   `json:"reimbursementCurrencyAmountDue,omitzero"`
	ReimbursementCurrencyCashAdvanceAmount autotask.Optional[float64]   `json:"reimbursementCurrencyCashAdvanceAmount,omitzero"`
	ReimbursementCurrencyID                autotask.Optional[int64]     `json:"reimbursementCurrencyID,omitzero"`
	RejectionReason                        autotask.Optional[string]    `json:"rejectionReason,omitzero"`
	Status                                 autotask.Optional[int64]     `json:"status,omitzero"`
	Submit                                 autotask.Optional[bool]      `json:"submit,omitzero"`
	SubmitDate                             autotask.Optional[time.Time] `json:"submitDate,omitzero"`
	SubmitterID                            autotask.Optional[int64]     `json:"submitterID,omitzero"`
	WeekEnding                             autotask.Optional[time.Time] `json:"weekEnding,omitzero"`
	UserDefinedFields                      []autotask.UDF               `json:"userDefinedFields,omitempty"`
}

func (ExpenseReport) EntityName() string { return "ExpenseReports" }
