// Code generated by autotask-gen. DO NOT EDIT.
package entities

import (
	"time"

	autotask "github.com/tphakala/go-autotask"
)

// Invoice represents an Autotask Invoice entity.
type Invoice struct {
	BatchID                      autotask.Optional[int64]     `json:"batchID,omitzero"`
	Comments                     autotask.Optional[string]    `json:"comments,omitzero"`
	CompanyID                    autotask.Optional[int64]     `json:"companyID,omitzero"`
	CreateDateTime               autotask.Optional[time.Time] `json:"createDateTime,omitzero"`
	CreatorResourceID            autotask.Optional[int64]     `json:"creatorResourceID,omitzero"`
	DueDate                      autotask.Optional[time.Time] `json:"dueDate,omitzero"`
	FromDate                     autotask.Optional[time.Time] `json:"fromDate,omitzero"`
	ID                           autotask.Optional[int64]     `json:"id,omitzero"`
	InvoiceDateTime              autotask.Optional[time.Time] `json:"invoiceDateTime,omitzero"`
	InvoiceEditorTemplateID      autotask.Optional[int64]     `json:"invoiceEditorTemplateID,omitzero"`
	InvoiceNumber                autotask.Optional[string]    `json:"invoiceNumber,omitzero"`
	InvoiceStatus                autotask.Optional[int64]     `json:"invoiceStatus,omitzero"`
	InvoiceTaxMethodExternalCode autotask.Optional[string]    `json:"invoiceTaxMethodExternalCode,omitzero"`
	InvoiceTotal                 autotask.Optional[float64]   `json:"invoiceTotal,omitzero"`
	IsVoided                     autotask.Optional[bool]      `json:"isVoided,omitzero"`
	OrderNumber                  autotask.Optional[string]    `json:"orderNumber,omitzero"`
	PaidDate                     autotask.Optional[time.Time] `json:"paidDate,omitzero"`
	PaymentTerm                  autotask.Optional[int64]     `json:"paymentTerm,omitzero"`
	TaxGroup                     autotask.Optional[int64]     `json:"taxGroup,omitzero"`
	TaxRegionName                autotask.Optional[string]    `json:"taxRegionName,omitzero"`
	ToDate                       autotask.Optional[time.Time] `json:"toDate,omitzero"`
	TotalTaxValue                autotask.Optional[float64]   `json:"totalTaxValue,omitzero"`
	VoidedByResourceID           autotask.Optional[int64]     `json:"voidedByResourceID,omitzero"`
	VoidedDate                   autotask.Optional[time.Time] `json:"voidedDate,omitzero"`
	WebServiceDate               autotask.Optional[time.Time] `json:"webServiceDate,omitzero"`
	UserDefinedFields            []autotask.UDF               `json:"userDefinedFields,omitempty"`
}

func (Invoice) EntityName() string { return "Invoices" }
