// Code generated by autotask-gen. DO NOT EDIT.
package entities

import (
	"time"

	autotask "github.com/tphakala/go-autotask"
)

// Opportunity represents an Autotask Opportunity entity.
type Opportunity struct {
	AdvancedField1                   autotask.Optional[float64]   `json:"advancedField1,omitzero"`
	AdvancedField2                   autotask.Optional[float64]   `json:"advancedField2,omitzero"`
	AdvancedField3                   autotask.Optional[float64]   `json:"advancedField3,omitzero"`
	AdvancedField4                   autotask.Optional[float64]   `json:"advancedField4,omitzero"`
	AdvancedField5                   autotask.Optional[float64]   `json:"advancedField5,omitzero"`
	Amount                           autotask.Optional[float64]   `json:"amount,omitzero"`
	AssessmentScore                  autotask.Optional[float64]   `json:"assessmentScore,omitzero"`
	Barriers                         autotask.Optional[string]    `json:"barriers,omitzero"`
	ClosedDate                       autotask.Optional[time.Time] `json:"closedDate,omitzero"`
	CompanyID                        autotask.Optional[int64]     `json:"companyID,omitzero"`
	ContactID                        autotask.Optional[int64]     `json:"contactID,omitzero"`
	Cost                             autotask.Optional[float64]   `json:"cost,omitzero"`
	CreateDate                       autotask.Optional[time.Time] `json:"createDate,omitzero"`
	CreatorResourceID                autotask.Optional[int64]     `json:"creatorResourceID,omitzero"`
	Description                      autotask.Optional[string]    `json:"description,omitzero"`
	HelpNeeded                       autotask.Optional[string]    `json:"helpNeeded,omitzero"`
	Id                               autotask.Optional[int64]     `json:"id,omitzero"`
	ImpersonatorCreatorResourceID    autotask.Optional[int64]     `json:"impersonatorCreatorResourceID,omitzero"`
	LastActivity                     autotask.Optional[time.Time] `json:"lastActivity,omitzero"`
	LeadSource                       autotask.Optional[int64]     `json:"leadSource,omitzero"`
	LossReason                       autotask.Optional[int64]     `json:"lossReason,omitzero"`
	LossReasonDetail                 autotask.Optional[string]    `json:"lossReasonDetail,omitzero"`
	LostDate                         autotask.Optional[time.Time] `json:"lostDate,omitzero"`
	Market                           autotask.Optional[string]    `json:"market,omitzero"`
	MonthlyCost                      autotask.Optional[float64]   `json:"monthlyCost,omitzero"`
	MonthlyRevenue                   autotask.Optional[float64]   `json:"monthlyRevenue,omitzero"`
	NextStep                         autotask.Optional[string]    `json:"nextStep,omitzero"`
	OnetimeCost                      autotask.Optional[float64]   `json:"onetimeCost,omitzero"`
	OnetimeRevenue                   autotask.Optional[float64]   `json:"onetimeRevenue,omitzero"`
	OpportunityCategoryID            autotask.Optional[int64]     `json:"opportunityCategoryID,omitzero"`
	OrganizationalLevelAssociationID autotask.Optional[int64]     `json:"organizationalLevelAssociationID,omitzero"`
	OwnerResourceID                  autotask.Optional[int64]     `json:"ownerResourceID,omitzero"`
	PrimaryCompetitor                autotask.Optional[int64]     `json:"primaryCompetitor,omitzero"`
	Probability                      autotask.Optional[int64]     `json:"probability,omitzero"`
	ProductID                        autotask.Optional[int64]     `json:"productID,omitzero"`
	ProjectedCloseDate               autotask.Optional[time.Time] `json:"projectedCloseDate,omitzero"`
	PromisedFulfillmentDate          autotask.Optional[time.Time] `json:"promisedFulfillmentDate,omitzero"`
	PromotionName                    autotask.Optional[string]    `json:"promotionName,omitzero"`
	QuarterlyCost                    autotask.Optional[float64]   `json:"quarterlyCost,omitzero"`
	QuarterlyRevenue                 autotask.Optional[float64]   `json:"quarterlyRevenue,omitzero"`
	Rating                           autotask.Optional[int64]     `json:"rating,omitzero"`
	RelationshipAssessmentScore      autotask.Optional[float64]   `json:"relationshipAssessmentScore,omitzero"`
	RevenueSpread                    autotask.Optional[int64]     `json:"revenueSpread,omitzero"`
	RevenueSpreadUnit                autotask.Optional[string]    `json:"revenueSpreadUnit,omitzero"`
	SalesOrderID                     autotask.Optional[int64]     `json:"salesOrderID,omitzero"`
	SalesProcessPercentComplete      autotask.Optional[float64]   `json:"salesProcessPercentComplete,omitzero"`
	SemiannualCost                   autotask.Optional[float64]   `json:"semiannualCost,omitzero"`
	SemiannualRevenue                autotask.Optional[float64]   `json:"semiannualRevenue,omitzero"`
	Stage                            autotask.Optional[int64]     `json:"stage,omitzero"`
	StartDate                        autotask.Optional[time.Time] `json:"startDate,omitzero"`
	Status                           autotask.Optional[int64]     `json:"status,omitzero"`
	TechnicalAssessmentScore         autotask.Optional[float64]   `json:"technicalAssessmentScore,omitzero"`
	ThroughDate                      autotask.Optional[time.Time] `json:"throughDate,omitzero"`
	Title                            autotask.Optional[string]    `json:"title,omitzero"`
	TotalAmountMonths                autotask.Optional[int64]     `json:"totalAmountMonths,omitzero"`
	UseQuoteTotals                   autotask.Optional[bool]      `json:"useQuoteTotals,omitzero"`
	WinReason                        autotask.Optional[int64]     `json:"winReason,omitzero"`
	WinReasonDetail                  autotask.Optional[string]    `json:"winReasonDetail,omitzero"`
	YearlyCost                       autotask.Optional[float64]   `json:"yearlyCost,omitzero"`
	YearlyRevenue                    autotask.Optional[float64]   `json:"yearlyRevenue,omitzero"`
	UserDefinedFields                []autotask.UDF               `json:"userDefinedFields,omitempty"`
}

func (Opportunity) EntityName() string { return "Opportunities" }
