// Code generated by autotask-gen. DO NOT EDIT.
package entities

import (
	"time"

	autotask "github.com/tphakala/go-autotask"
)

// Product represents an Autotask Product entity.
type Product struct {
	BillingType                       autotask.Optional[int64]     `json:"billingType,omitzero"`
	ChargeBillingCodeID               autotask.Optional[int64]     `json:"chargeBillingCodeID,omitzero"`
	CreatedByResourceID               autotask.Optional[int64]     `json:"createdByResourceID,omitzero"`
	CreatedTime                       autotask.Optional[time.Time] `json:"createdTime,omitzero"`
	DefaultInstalledProductCategoryID autotask.Optional[int64]     `json:"defaultInstalledProductCategoryID,omitzero"`
	DefaultVendorID                   autotask.Optional[int64]     `json:"defaultVendorID,omitzero"`
	Description                       autotask.Optional[string]    `json:"description,omitzero"`
	DoesNotRequireProcurement         autotask.Optional[bool]      `json:"doesNotRequireProcurement,omitzero"`
	ExternalProductID                 autotask.Optional[string]    `json:"externalProductID,omitzero"`
	ID                                autotask.Optional[int64]     `json:"id,omitzero"`
	ImpersonatorCreatorResourceID     autotask.Optional[int64]     `json:"impersonatorCreatorResourceID,omitzero"`
	InternalProductID                 autotask.Optional[string]    `json:"internalProductID,omitzero"`
	IsActive                          autotask.Optional[bool]      `json:"isActive,omitzero"`
	IsEligibleForRma                  autotask.Optional[bool]      `json:"isEligibleForRma,omitzero"`
	IsSerialized                      autotask.Optional[bool]      `json:"isSerialized,omitzero"`
	Link                              autotask.Optional[string]    `json:"link,omitzero"`
	ManufacturerName                  autotask.Optional[string]    `json:"manufacturerName,omitzero"`
	ManufacturerProductName           autotask.Optional[string]    `json:"manufacturerProductName,omitzero"`
	MarkupRate                        autotask.Optional[float64]   `json:"markupRate,omitzero"`
	Msrp                              autotask.Optional[float64]   `json:"msrp,omitzero"`
	Name                              autotask.Optional[string]    `json:"name,omitzero"`
	PeriodType                        autotask.Optional[int64]     `json:"periodType,omitzero"`
	PriceCostMethod                   autotask.Optional[int64]     `json:"priceCostMethod,omitzero"`
	ProductBillingCodeID              autotask.Optional[int64]     `json:"productBillingCodeID,omitzero"`
	ProductCategory                   autotask.Optional[int64]     `json:"productCategory,omitzero"`
	Sku                               autotask.Optional[string]    `json:"sku,omitzero"`
	UnitCost                          autotask.Optional[float64]   `json:"unitCost,omitzero"`
	UnitPrice                         autotask.Optional[float64]   `json:"unitPrice,omitzero"`
	VendorProductNumber               autotask.Optional[string]    `json:"vendorProductNumber,omitzero"`
	UserDefinedFields                 []autotask.UDF               `json:"userDefinedFields,omitempty"`
}

func (Product) EntityName() string { return "Products" }
