// Code generated by autotask-gen. DO NOT EDIT.
package entities

import (
	"time"

	autotask "github.com/tphakala/go-autotask"
)

// ProjectNote represents an Autotask ProjectNote entity.
type ProjectNote struct {
	CreateDateTime                autotask.Optional[time.Time] `json:"createDateTime,omitzero"`
	CreatedByContactID            autotask.Optional[int64]     `json:"createdByContactID,omitzero"`
	CreatorResourceID             autotask.Optional[int64]     `json:"creatorResourceID,omitzero"`
	Description                   autotask.Optional[string]    `json:"description,omitzero"`
	ID                            autotask.Optional[int64]     `json:"id,omitzero"`
	ImpersonatorCreatorResourceID autotask.Optional[int64]     `json:"impersonatorCreatorResourceID,omitzero"`
	ImpersonatorUpdaterResourceID autotask.Optional[int64]     `json:"impersonatorUpdaterResourceID,omitzero"`
	IsAnnouncement                autotask.Optional[bool]      `json:"isAnnouncement,omitzero"`
	LastActivityDate              autotask.Optional[time.Time] `json:"lastActivityDate,omitzero"`
	NoteType                      autotask.Optional[int64]     `json:"noteType,omitzero"`
	ProjectID                     autotask.Optional[int64]     `json:"projectID,omitzero"`
	Publish                       autotask.Optional[int64]     `json:"publish,omitzero"`
	Title                         autotask.Optional[string]    `json:"title,omitzero"`
	UserDefinedFields             []autotask.UDF               `json:"userDefinedFields,omitempty"`
}

func (ProjectNote) EntityName() string { return "ProjectNotes" }
