// Code generated by autotask-gen. DO NOT EDIT.
package entities

import (
	autotask "github.com/tphakala/go-autotask"
)

// QuoteItem represents an Autotask QuoteItem entity.
type QuoteItem struct {
	AverageCost                  autotask.Optional[float64] `json:"averageCost,omitzero"`
	ChargeID                     autotask.Optional[int64]   `json:"chargeID,omitzero"`
	Description                  autotask.Optional[string]  `json:"description,omitzero"`
	ExpenseID                    autotask.Optional[int64]   `json:"expenseID,omitzero"`
	HighestCost                  autotask.Optional[float64] `json:"highestCost,omitzero"`
	Id                           autotask.Optional[int64]   `json:"id,omitzero"`
	InternalCurrencyLineDiscount autotask.Optional[float64] `json:"internalCurrencyLineDiscount,omitzero"`
	InternalCurrencyUnitDiscount autotask.Optional[float64] `json:"internalCurrencyUnitDiscount,omitzero"`
	InternalCurrencyUnitPrice    autotask.Optional[float64] `json:"internalCurrencyUnitPrice,omitzero"`
	IsOptional                   autotask.Optional[bool]    `json:"isOptional,omitzero"`
	IsTaxable                    autotask.Optional[bool]    `json:"isTaxable,omitzero"`
	LaborID                      autotask.Optional[int64]   `json:"laborID,omitzero"`
	LineDiscount                 autotask.Optional[float64] `json:"lineDiscount,omitzero"`
	MarkupRate                   autotask.Optional[float64] `json:"markupRate,omitzero"`
	Name                         autotask.Optional[string]  `json:"name,omitzero"`
	PercentageDiscount           autotask.Optional[float64] `json:"percentageDiscount,omitzero"`
	PeriodType                   autotask.Optional[int64]   `json:"periodType,omitzero"`
	ProductID                    autotask.Optional[int64]   `json:"productID,omitzero"`
	Quantity                     autotask.Optional[float64] `json:"quantity,omitzero"`
	QuoteID                      autotask.Optional[int64]   `json:"quoteID,omitzero"`
	QuoteItemType                autotask.Optional[int64]   `json:"quoteItemType,omitzero"`
	ServiceBundleID              autotask.Optional[int64]   `json:"serviceBundleID,omitzero"`
	ServiceID                    autotask.Optional[int64]   `json:"serviceID,omitzero"`
	ShippingID                   autotask.Optional[int64]   `json:"shippingID,omitzero"`
	SortOrderID                  autotask.Optional[int64]   `json:"sortOrderID,omitzero"`
	TaxCategoryID                autotask.Optional[int64]   `json:"taxCategoryID,omitzero"`
	TotalEffectiveTax            autotask.Optional[float64] `json:"totalEffectiveTax,omitzero"`
	UnitCost                     autotask.Optional[float64] `json:"unitCost,omitzero"`
	UnitDiscount                 autotask.Optional[float64] `json:"unitDiscount,omitzero"`
	UnitPrice                    autotask.Optional[float64] `json:"unitPrice,omitzero"`
	UserDefinedFields            []autotask.UDF             `json:"userDefinedFields,omitempty"`
}

func (QuoteItem) EntityName() string { return "QuoteItems" }
