// Code generated by autotask-gen. DO NOT EDIT.
package entities

import (
	"time"

	autotask "github.com/tphakala/go-autotask"
)

// Quote represents an Autotask Quote entity.
type Quote struct {
	ApprovalStatus                    autotask.Optional[int64]     `json:"approvalStatus,omitzero"`
	ApprovalStatusChangedByResourceID autotask.Optional[int64]     `json:"approvalStatusChangedByResourceID,omitzero"`
	ApprovalStatusChangedDate         autotask.Optional[time.Time] `json:"approvalStatusChangedDate,omitzero"`
	BillToLocationID                  autotask.Optional[int64]     `json:"billToLocationID,omitzero"`
	CalculateTaxSeparately            autotask.Optional[bool]      `json:"calculateTaxSeparately,omitzero"`
	Comment                           autotask.Optional[string]    `json:"comment,omitzero"`
	CompanyID                         autotask.Optional[int64]     `json:"companyID,omitzero"`
	ContactID                         autotask.Optional[int64]     `json:"contactID,omitzero"`
	CreateDate                        autotask.Optional[time.Time] `json:"createDate,omitzero"`
	CreatorResourceID                 autotask.Optional[int64]     `json:"creatorResourceID,omitzero"`
	Description                       autotask.Optional[string]    `json:"description,omitzero"`
	EffectiveDate                     autotask.Optional[time.Time] `json:"effectiveDate,omitzero"`
	ExpirationDate                    autotask.Optional[time.Time] `json:"expirationDate,omitzero"`
	ExtApprovalContactResponse        autotask.Optional[int64]     `json:"extApprovalContactResponse,omitzero"`
	ExtApprovalResponseDate           autotask.Optional[time.Time] `json:"extApprovalResponseDate,omitzero"`
	ExtApprovalResponseSignature      autotask.Optional[string]    `json:"extApprovalResponseSignature,omitzero"`
	ExternalQuoteNumber               autotask.Optional[string]    `json:"externalQuoteNumber,omitzero"`
	GroupByID                         autotask.Optional[int64]     `json:"groupByID,omitzero"`
	ID                                autotask.Optional[int64]     `json:"id,omitzero"`
	ImpersonatorCreatorResourceID     autotask.Optional[int64]     `json:"impersonatorCreatorResourceID,omitzero"`
	IsActive                          autotask.Optional[bool]      `json:"isActive,omitzero"`
	LastActivityDate                  autotask.Optional[time.Time] `json:"lastActivityDate,omitzero"`
	LastModifiedBy                    autotask.Optional[int64]     `json:"lastModifiedBy,omitzero"`
	LastPublishedByResourceID         autotask.Optional[int64]     `json:"lastPublishedByResourceID,omitzero"`
	LastPublishedDateTime             autotask.Optional[time.Time] `json:"lastPublishedDateTime,omitzero"`
	Name                              autotask.Optional[string]    `json:"name,omitzero"`
	OpportunityID                     autotask.Optional[int64]     `json:"opportunityID,omitzero"`
	PaymentTerm                       autotask.Optional[int64]     `json:"paymentTerm,omitzero"`
	PaymentType                       autotask.Optional[int64]     `json:"paymentType,omitzero"`
	PrimaryQuote                      autotask.Optional[bool]      `json:"primaryQuote,omitzero"`
	ProposalProjectID                 autotask.Optional[int64]     `json:"proposalProjectID,omitzero"`
	PurchaseOrderNumber               autotask.Optional[string]    `json:"purchaseOrderNumber,omitzero"`
	QuoteNumber                       autotask.Optional[int64]     `json:"quoteNumber,omitzero"`
	QuoteTemplateID                   autotask.Optional[int64]     `json:"quoteTemplateID,omitzero"`
	ShippingType                      autotask.Optional[int64]     `json:"shippingType,omitzero"`
	ShipToLocationID                  autotask.Optional[int64]     `json:"shipToLocationID,omitzero"`
	ShowEachTaxInGroup                autotask.Optional[bool]      `json:"showEachTaxInGroup,omitzero"`
	ShowTaxCategory                   autotask.Optional[bool]      `json:"showTaxCategory,omitzero"`
	SoldToLocationID                  autotask.Optional[int64]     `json:"soldToLocationID,omitzero"`
	TaxRegionID                       autotask.Optional[int64]     `json:"taxRegionID,omitzero"`
	UserDefinedFields                 []autotask.UDF               `json:"userDefinedFields,omitempty"`
}

func (Quote) EntityName() string { return "Quotes" }
