// Code generated by autotask-gen. DO NOT EDIT.
package entities

import (
	"time"

	autotask "github.com/tphakala/go-autotask"
)

// Service represents an Autotask Service entity.
type Service struct {
	BillingCodeID                            autotask.Optional[int64]     `json:"billingCodeID,omitzero"`
	CatalogNumberPartNumber                  autotask.Optional[string]    `json:"catalogNumberPartNumber,omitzero"`
	CreateDate                               autotask.Optional[time.Time] `json:"createDate,omitzero"`
	CreatorResourceID                        autotask.Optional[int64]     `json:"creatorResourceID,omitzero"`
	Description                              autotask.Optional[string]    `json:"description,omitzero"`
	ExternalID                               autotask.Optional[string]    `json:"externalID,omitzero"`
	Id                                       autotask.Optional[int64]     `json:"id,omitzero"`
	InternalID                               autotask.Optional[string]    `json:"internalID,omitzero"`
	InvoiceDescription                       autotask.Optional[string]    `json:"invoiceDescription,omitzero"`
	IsActive                                 autotask.Optional[bool]      `json:"isActive,omitzero"`
	LastModifiedDate                         autotask.Optional[time.Time] `json:"lastModifiedDate,omitzero"`
	ManufacturerServiceProvider              autotask.Optional[string]    `json:"manufacturerServiceProvider,omitzero"`
	ManufacturerServiceProviderProductNumber autotask.Optional[string]    `json:"manufacturerServiceProviderProductNumber,omitzero"`
	MarkupRate                               autotask.Optional[float64]   `json:"markupRate,omitzero"`
	Name                                     autotask.Optional[string]    `json:"name,omitzero"`
	PeriodType                               autotask.Optional[int64]     `json:"periodType,omitzero"`
	ServiceLevelAgreementID                  autotask.Optional[int64]     `json:"serviceLevelAgreementID,omitzero"`
	Sku                                      autotask.Optional[string]    `json:"sku,omitzero"`
	UnitCost                                 autotask.Optional[float64]   `json:"unitCost,omitzero"`
	UnitPrice                                autotask.Optional[float64]   `json:"unitPrice,omitzero"`
	UpdateResourceID                         autotask.Optional[int64]     `json:"updateResourceID,omitzero"`
	Url                                      autotask.Optional[string]    `json:"url,omitzero"`
	VendorCompanyID                          autotask.Optional[int64]     `json:"vendorCompanyID,omitzero"`
	UserDefinedFields                        []autotask.UDF               `json:"userDefinedFields,omitempty"`
}

func (Service) EntityName() string { return "Services" }
