// Code generated by autotask-gen. DO NOT EDIT.
package entities

import (
	"time"

	autotask "github.com/tphakala/go-autotask"
)

// TicketAttachment represents an Autotask TicketAttachment entity.
type TicketAttachment struct {
	AttachDate                    autotask.Optional[time.Time] `json:"attachDate,omitzero"`
	AttachedByContactID           autotask.Optional[int64]     `json:"attachedByContactID,omitzero"`
	AttachedByResourceID          autotask.Optional[int64]     `json:"attachedByResourceID,omitzero"`
	AttachmentType                autotask.Optional[string]    `json:"attachmentType,omitzero"`
	ContentType                   autotask.Optional[string]    `json:"contentType,omitzero"`
	CreatorType                   autotask.Optional[int64]     `json:"creatorType,omitzero"`
	Data                          autotask.Optional[string]    `json:"data,omitzero"`
	FileSize                      autotask.Optional[int64]     `json:"fileSize,omitzero"`
	FullPath                      autotask.Optional[string]    `json:"fullPath,omitzero"`
	ID                            autotask.Optional[int64]     `json:"id,omitzero"`
	ImpersonatorCreatorResourceID autotask.Optional[int64]     `json:"impersonatorCreatorResourceID,omitzero"`
	OpportunityID                 autotask.Optional[int64]     `json:"opportunityID,omitzero"`
	ParentAttachmentID            autotask.Optional[int64]     `json:"parentAttachmentID,omitzero"`
	ParentID                      autotask.Optional[int64]     `json:"parentID,omitzero"`
	Publish                       autotask.Optional[int64]     `json:"publish,omitzero"`
	TicketID                      autotask.Optional[int64]     `json:"ticketID,omitzero"`
	TicketNoteID                  autotask.Optional[int64]     `json:"ticketNoteID,omitzero"`
	TimeEntryID                   autotask.Optional[int64]     `json:"timeEntryID,omitzero"`
	Title                         autotask.Optional[string]    `json:"title,omitzero"`
	UserDefinedFields             []autotask.UDF               `json:"userDefinedFields,omitempty"`
}

func (TicketAttachment) EntityName() string { return "TicketAttachments" }
