package main

import (
	"context"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	autotask "github.com/tphakala/go-autotask"
	"github.com/tphakala/go-autotask/metadata"
)

const (
	dirPerm  = 0o755
	filePerm = 0o644
)

// DefaultEntities is the full set of entities generated when no -entities flag is provided.
var DefaultEntities = []string{
	"Tickets", "Companies", "Contacts", "Projects", "Tasks",
	"Contracts", "ConfigurationItems", "Resources", "TimeEntries",
	"ProjectNotes", "CompanyNotes",
	"TicketAttachments",
	"Quotes", "QuoteItems", "Opportunities",
	"Invoices", "BillingItems", "BillingItemApprovalLevels", "BillingCodes",
	"ExpenseReports", "ExpenseItems",
	"Products", "Services", "ServiceBundles",
	"Departments",
}

type Generator struct {
	Client    *autotask.Client
	OutputDir string
	Entities  []string // if empty, uses DefaultEntities
}

func (g *Generator) Generate(ctx context.Context) error {
	if err := os.MkdirAll(g.OutputDir, dirPerm); err != nil {
		return fmt.Errorf("creating output dir: %w", err)
	}
	entities := g.Entities
	if len(entities) == 0 {
		entities = DefaultEntities
	}
	for _, entityName := range entities {
		fields, err := metadata.GetFields(ctx, g.Client, entityName)
		if err != nil {
			fmt.Fprintf(os.Stderr, "warning: skipping %s: %v\n", entityName, err)
			continue
		}
		udfs, err := metadata.GetUDFs(ctx, g.Client, entityName)
		if err != nil {
			fmt.Fprintf(os.Stderr, "warning: %s: could not fetch UDFs: %v\n", entityName, err)
		}
		if err := g.generateEntity(entityName, fields, udfs); err != nil {
			return fmt.Errorf("generating %s: %w", entityName, err)
		}
		fmt.Printf("Generated %s\n", entityName)
	}
	return nil
}

// toSnakeCase converts PascalCase to snake_case, handling acronyms.
// "TicketNotes" -> "ticket_notes", "HTTPServer" -> "http_server", "APIKey" -> "api_key"
func toSnakeCase(s string) string {
	var result []byte
	b := []byte(s)
	for i, r := range b {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				prev := b[i-1]
				// Insert underscore before uppercase that follows lowercase: "ticketN" -> "ticket_n"
				if prev >= 'a' && prev <= 'z' {
					result = append(result, '_')
				} else if prev >= 'A' && prev <= 'Z' && i+1 < len(b) && b[i+1] >= 'a' && b[i+1] <= 'z' && i >= 2 && b[i-2] >= 'A' && b[i-2] <= 'Z' {
					// Acronym boundary: 3+ uppercase run followed by lowercase.
					// "HTTPServer" at S: b[i-2]=T(upper), prev=P(upper), next=e(lower) → underscore
					// "IDs" at D: i<2 → no underscore → "ids" (correct)
					result = append(result, '_')
				}
			}
			result = append(result, r+('a'-'A'))
		} else {
			result = append(result, r)
		}
	}
	return string(result)
}

func (g *Generator) generateEntity(name string, fields []metadata.FieldInfo, udfs []metadata.UDFInfo) error {
	filename := toSnakeCase(name) + ".go"
	path := filepath.Join(g.OutputDir, filename)
	var buf strings.Builder
	if err := entityTemplate.Execute(&buf, entityData{Name: name, Fields: fields, UDFs: udfs}); err != nil {
		return err
	}
	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		_ = os.WriteFile(path, []byte(buf.String()), filePerm)
		return fmt.Errorf("formatting generated code for %s: %w", name, err)
	}
	return os.WriteFile(path, formatted, filePerm)
}

type entityData struct {
	Name   string
	Fields []metadata.FieldInfo
	UDFs   []metadata.UDFInfo
}

var entityTemplate = template.Must(template.New("entity").Funcs(template.FuncMap{
	"goType":   goType,
	"goName":   goName,
	"singular": singular,
}).Parse(`// Code generated by autotask-gen. DO NOT EDIT.
package entities

import (
	"time"

	autotask "github.com/tphakala/go-autotask"
)

// {{singular .Name}} represents an Autotask {{singular .Name}} entity.
type {{singular .Name}} struct {
{{- range .Fields}}
	{{goName .Name}} autotask.Optional[{{goType .Type}}] ` + "`" + `json:"{{.Name}},omitzero"` + "`" + `
{{- end}}
	UserDefinedFields []autotask.UDF ` + "`" + `json:"userDefinedFields,omitempty"` + "`" + `
}

func ({{singular .Name}}) EntityName() string { return "{{.Name}}" }
`))

func goType(atType string) string {
	switch strings.ToLower(atType) {
	case "integer", "long":
		return "int64"
	case "short":
		return "int"
	case "double", "decimal":
		return "float64"
	case "boolean":
		return "bool"
	case "datetime":
		return "time.Time"
	default:
		return "string"
	}
}

func goName(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

// irregularPlurals maps entity names whose pluralization cannot be handled
// by simple suffix rules without producing incorrect results.
var irregularPlurals = map[string]string{
	"Statuses":  "Status",
	"Addresses": "Address",
}

func singular(s string) string {
	if v, ok := irregularPlurals[s]; ok {
		return v
	}
	if strings.HasSuffix(s, "ies") {
		return s[:len(s)-3] + "y"
	}
	return strings.TrimSuffix(s, "s")
}
